# This file sources other files in `hyprland` and `custom` folders
# You wanna add your stuff in files in `custom`

$qsConfig = ii
exec = hyprctl dispatch submap global # DO NOT REMOVE THIS OR YOU WON'T BE ABLE TO USE ANY KEYBIND
submap = global # This is required for catchall to work

# Environment variables
source=hyprland/env.conf
source=custom/env.conf

# Defaults
source=hyprland/execs.conf
source=hyprland/general.conf
source=hyprland/rules.conf
source=hyprland/colors.conf
source=hyprland/keybinds.conf

# Custom 
source=custom/execs.conf
source=custom/general.conf
source=custom/rules.conf
source=custom/keybinds.conf

# nwg-displays support
source=workspaces.conf
source=monitors.conf
# = Source for hyprviz
source = ./hyprviz.conf


exec-once = bongocat --config ~/.config/bongocat.conf

# decoration {
#     rounding = 18
#     rounding_power = 2.4
# 
#     blur {
#         enabled = true
#         size = 10
#         passes = 3
#         new_optimizations = true
#         xray = true
#         brightness = 1
#         noise = 0.05
#         contrast = 0.89
#         vibrancy = 0.5
#         vibrancy_darkness = 0.5
#     }
# 
#     shadow {
#         enabled = true
#     }
# }
# # Modern 0.53+ syntax for setting Kitty's opacity (0.85 active, 0.85 inactive)
# windowrule = match:class ^(kitty)$, opacity 0.99 0.99