# Navigation
LEFT  seek -5
RIGHT seek 5
UP    seek 60
DOWN  seek -60
[     no-osd multiply speed 1/1.1; script-binding uosc/flash-speed
]     no-osd multiply speed 1.1; script-binding uosc/flash-speed
\     no-osd set speed 1; script-binding uosc/flash-speed
Alt+LEFT  add chapter -1
Alt+RIGHT add chapter 1

# Volume
m       no-osd cycle mute; script-binding uosc/flash-volume
9       no-osd add volume -5; script-binding uosc/flash-volume
0       no-osd add volume 5; script-binding uosc/flash-volume

# Toggle UI
tab     script-binding uosc/toggle-ui
T       script-binding uosc/toggle-title

# Menus
Shift+s     script-binding uosc/subtitles          #! Subtitles
a           script-binding uosc/audio              #! Audio tracks
v           script-binding uosc/video              #! Video tracks
q           script-binding uosc/stream-quality     #! Stream quality
p           script-binding uosc/playlist           #! Playlist
c           script-binding uosc/chapters           #! Chapters
o           script-binding uosc/open-file          #! Open file
d           script-binding uosc/download-subtitles #! Download subtitles
#           script-binding uosc/editions           #! Utils > Editions
O           script-binding uosc/keybinds           #! Utils > Key bindings

# Playlist / directory
>     script-binding uosc/next               #! Navigation > Next
<     script-binding uosc/prev               #! Navigation > Prev
Alt+> script-binding uosc/delete-file-next   #! Navigation > Delete file & Next
Alt+< script-binding uosc/delete-file-prev   #! Navigation > Delete file & Prev

# Screenshot
b       async screenshot subtitles                   #! Utils > Screenshot (with subs)
ctrl+s  async screenshot                             #! Utils > Screenshot
ctrl+shift+s async screenshot subtitles              #! Utils > Screenshot (with subs)

# Playback
SPACE cycle pause
enter script-binding uosc/menu
ESC   quit
